server:
  port: 80
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: Moshoukknd1012.
#    key-store-type: PKCS12
#    key-alias: tomcat
    
spring:
  jpa:  
    database : MYSQL  
    show-sql : true  
    hibernate:  
      ddl-auto : update  
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy  
    properties:  
      hibernate:  
        dialect : org.hibernate.dialect.MySQL5Dialect   
  datasource:
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Zheng1234
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    
    
  
